version: '3.4'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"